In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('diabetes.csv')

In [3]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
data.shape

(768, 9)

In [5]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [7]:
import numpy as np
data['Glucose'] = np.where(data['Glucose']==0,data['Glucose'].median(),data['Glucose'])
data['Insulin'] = np.where(data['Insulin']==0,data['Insulin'].median(),data['Insulin'])
data['BloodPressure'] = np.where(data['BloodPressure']==0,data['BloodPressure'].median(),data['BloodPressure'])
data['SkinThickness'] = np.where(data['SkinThickness']==0,data['SkinThickness'].median(),data['SkinThickness'])
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6    148.0           72.0           35.0     30.5  33.6   
1            1     85.0           66.0           29.0     30.5  26.6   
2            8    183.0           64.0           23.0     30.5  23.3   
3            1     89.0           66.0           23.0     94.0  28.1   
4            0    137.0           40.0           35.0    168.0  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [8]:
data.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  121.656250      72.386719      27.334635   94.652344   
std       3.369578   30.438286      12.096642       9.229014  105.547598   
min       0.000000   44.000000      24.000000       7.000000   14.000000   
25%       1.000000   99.750000      64.000000      23.000000   30.500000   
50%       3.000000  117.000000      72.000000      23.000000   31.250000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [9]:
x= data.drop('Outcome',axis=1)
y= data['Outcome']
print(x.shape)
print(y.shape)

(768, 8)
(768,)


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)


In [11]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier(n_estimators=10,).fit(x_train,y_train)
pridiction = model.predict(x_test)

In [12]:
from sklearn.metrics import confusion_matrix,accuracy_score,classification_report
print(confusion_matrix(y_test,pridiction))
print('******************************************')
print(accuracy_score(y_test,pridiction))
print('******************************************')
print(classification_report(y_test,pridiction))

[[82 17]
 [19 36]]
******************************************
0.7662337662337663
******************************************
              precision    recall  f1-score   support

           0       0.81      0.83      0.82        99
           1       0.68      0.65      0.67        55

    accuracy                           0.77       154
   macro avg       0.75      0.74      0.74       154
weighted avg       0.76      0.77      0.77       154



# Randomised search cv

In [13]:
from sklearn.model_selection import RandomizedSearchCV

n_estimators=[int(x) for x in np.linspace(start=100,stop=2000,num=15)]

max_depth=[int(x) for x in np.linspace(start=10,stop=1000,num=15)]

min_samples_split=[4,8,10,15,20]

min_samples_leaf=[2,5,8,10,15]

max_features=["auto", "sqrt", "log2"]

criterion=["gini", "entropy"]

random_grid = {'n_estimators':n_estimators,
              'max_depth':max_depth,
              'min_samples_split':min_samples_split,
              'min_samples_leaf':min_samples_leaf,
              'max_features':max_features,
              'criterion':criterion}
print(random_grid)

{'n_estimators': [100, 235, 371, 507, 642, 778, 914, 1050, 1185, 1321, 1457, 1592, 1728, 1864, 2000], 'max_depth': [10, 80, 151, 222, 292, 363, 434, 504, 575, 646, 717, 787, 858, 929, 1000], 'min_samples_split': [4, 8, 10, 15, 20], 'min_samples_leaf': [2, 5, 8, 10, 15], 'max_features': ['auto', 'sqrt', 'log2'], 'criterion': ['gini', 'entropy']}


In [14]:
rscv = RandomizedSearchCV(estimator=RandomForestClassifier(),param_distributions= random_grid,n_iter=8,cv=3,random_state=42,
                         n_jobs=-1,verbose=2)
rscv.fit(x_train,y_train)

Fitting 3 folds for each of 8 candidates, totalling 24 fits


RandomizedSearchCV(cv=3, estimator=RandomForestClassifier(), n_iter=8,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [10, 80, 151, 222, 292,
                                                      363, 434, 504, 575, 646,
                                                      717, 787, 858, 929,
                                                      1000],
                                        'max_features': ['auto', 'sqrt',
                                                         'log2'],
                                        'min_samples_leaf': [2, 5, 8, 10, 15],
                                        'min_samples_split': [4, 8, 10, 15, 20],
                                        'n_estimators': [100, 235, 371, 507,
                                                         642, 778, 914, 1050,
                                                         1185, 1321, 1457, 1592,

In [15]:
rscv.best_params_

{'n_estimators': 778,
 'min_samples_split': 10,
 'min_samples_leaf': 5,
 'max_features': 'log2',
 'max_depth': 10,
 'criterion': 'gini'}

In [22]:
temp = rscv.best_estimator_
temp

RandomForestClassifier(max_depth=10, max_features='log2', min_samples_leaf=5,
                       min_samples_split=10, n_estimators=778)

In [17]:
model_rscv = temp
model_rscv.fit(x_train,y_train)
predict_rscv = model_rscv.predict(x_test)

In [18]:
print(confusion_matrix(y_test,predict_rscv))
print('******************************************')
print(accuracy_score(y_test,predict_rscv))
print('******************************************')
print(classification_report(y_test,predict_rscv))

[[81 18]
 [17 38]]
******************************************
0.7727272727272727
******************************************
              precision    recall  f1-score   support

           0       0.83      0.82      0.82        99
           1       0.68      0.69      0.68        55

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154



# GridSearch cv 

In [19]:
 rscv.best_params_

{'n_estimators': 778,
 'min_samples_split': 10,
 'min_samples_leaf': 5,
 'max_features': 'log2',
 'max_depth': 10,
 'criterion': 'gini'}

In [24]:
from sklearn.model_selection import GridSearchCV
gscv_grid  = {'n_estimators': [rscv.best_params_['n_estimators'],
                              rscv.best_params_['n_estimators']+100,
                              rscv.best_params_['n_estimators']-100,
                              rscv.best_params_['n_estimators']+200],
              'max_depth':[rscv.best_params_['max_depth'],
                          rscv.best_params_['max_depth']+3,
                          rscv.best_params_['max_depth']+6,
                          rscv.best_params_['max_depth']-3],
              'min_samples_split':[rscv.best_params_['min_samples_split'],
                                  rscv.best_params_['min_samples_split']+2,
                                  rscv.best_params_['min_samples_split']-3],
              'min_samples_leaf':[rscv.best_params_['min_samples_leaf'],
                                 rscv.best_params_['min_samples_leaf']+5,
                                 rscv.best_params_['min_samples_leaf']+10],
              'max_features':[rscv.best_params_['max_features']],
              'criterion':[rscv.best_params_['criterion']]
    
}
print(gscv_grid)

{'n_estimators': [778, 878, 678, 978], 'max_depth': [10, 13, 16, 7], 'min_samples_split': [10, 12, 7], 'min_samples_leaf': [5, 10, 15], 'max_features': ['log2'], 'criterion': ['gini']}


In [25]:
gscv = GridSearchCV(estimator=RandomForestClassifier(),param_grid=gscv_grid,n_jobs=-1,cv=5,verbose=2)
gscv.fit(x_train,y_train)

Fitting 5 folds for each of 144 candidates, totalling 720 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini'], 'max_depth': [10, 13, 16, 7],
                         'max_features': ['log2'],
                         'min_samples_leaf': [5, 10, 15],
                         'min_samples_split': [10, 12, 7],
                         'n_estimators': [778, 878, 678, 978]},
             verbose=2)

In [31]:
gscv.best_estimator_

RandomForestClassifier(max_depth=16, max_features='log2', min_samples_leaf=5,
                       min_samples_split=12, n_estimators=778)

In [32]:
best_model = gscv.best_estimator_
prediction_after_hpt = best_model.predict(x_test)

In [33]:
print(confusion_matrix(y_test,prediction_after_hpt))
print('******************************************')
print(accuracy_score(y_test,prediction_after_hpt))
print('******************************************')
print(classification_report(y_test,prediction_after_hpt))

[[81 18]
 [17 38]]
******************************************
0.7727272727272727
******************************************
              precision    recall  f1-score   support

           0       0.83      0.82      0.82        99
           1       0.68      0.69      0.68        55

    accuracy                           0.77       154
   macro avg       0.75      0.75      0.75       154
weighted avg       0.77      0.77      0.77       154



# Automated Hyper parameter Tuning